Feature/security question database
HTiSolutions/poolref pull request #35
Opened 2017-03-26 13:43 UTC by gc15927

2017-03-26 13:44 UTC, bradleymiles17 commented on migration20170323_security-question.sql
> +VALUES ('7', "What is the name of your favorite pet?");
new line

2017-03-26 13:49 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/entities/User.java
> +    private Long security_question_id;
These variables should be Camel Case

i.e. securityQuestionId

2017-03-26 13:49 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/entities/User.java
> +    @Nullable
If Nullable is causing problems then just remove it, not essential

2017-03-26 13:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/viewModels/ResetPasswordNicknameViewModel.java
> + * Created by garethcarless on 24/03/2017.
Remove comment

2017-03-26 13:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/viewModels/ResetPasswordQuestionViewModel.java
> + * Created by garethcarless on 24/03/2017.
Same as above

2017-03-26 13:50 UTC, bradleymiles17 commented on src/main/resources/templates/views/reset-password-nickname.html
> +</html>
new line

2017-03-26 13:53 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +        nickname = resetPasswordNicknameViewModel.getNickname();
Should be using Id

2017-03-26 13:54 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +    ResetPasswordController(ResetPasswordService resetPasswordService){this.resetPasswordService = resetPasswordService;}
The methods in this controller are very confusing, you should just have two?

index()
reset()

2017-03-26 13:54 UTC, bradleymiles17 commented on migration20170323_security-question.sql
> +INSERT INTO `pool_ref`.`security_question` (id, question)
INSERT methods can perform multiple lines at once

This can be simplified and also would perform substantially less requests on migration

2017-03-27 20:38 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/RegisterService.java
> +                return false;
If you merge master into this branch, you can setup logging correctly

2017-03-27 20:39 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +                return false;
Log

2017-03-27 20:39 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/viewModels/SecurityQuestionViewModel.java
> + * Created by root on 23/03/2017.
Remove comment

2017-03-27 20:40 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/entities/User.java
> +    @Nullable
If nullable is causing errors remove it, you are importing it from a strange library anyway

2017-03-28 17:50 UTC, bradleymiles17 requested changes

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/entities/User.java
> +    private String hashed_password;
This needs to be camel case

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +}
New line

2017-03-28 17:50 UTC, bradleymiles17 commented on migration20170323_security-question.sql
> +VALUES ('1', "What is your mother's maiden name?"), ('2', "In what city were you born?"), ('3', "What secondary school did you attend?"), ('4', "What street did you grow up on?"), ('5', "What was the
👍

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +        else{
Can you run "reformat code" on this class, just to reorganise the code

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/entities/User.java
> +    public void setHashed_password(String password){hashed_password = password;}
Camel Case

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/RegisterService.java
> +                return false;
You will need to resolve the conflicts, pull master into your current branch

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +    private User user;
Do we want user to be global

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +    private boolean answeredQuestion;
Likewise, should this really be global?

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/SecurityQuestionService.java
> +                //"Error creating the user: " + ex.toString();
Once, merged master, create another Log

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/viewModels/ResetPasswordNicknameViewModel.java
> +package com.htisolutions.poolref.viewModels;
These ViewModels should probably be in another directory called "securityQuestion"

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/resources/templates/views/reset-password-password.html
> +</html>
new line

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/resources/templates/views/reset-password-question.html
> +</html>
new line

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/resources/templates/views/security-question.html
> +</html>
new line

PLEASE JUST TURN IT ON IN YOUR EDITOR

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +    private User user;
Should this be global

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +    private User user;
The methods should just pass the Id, and not rely on this being global

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/SecurityQuestionController.java
> +    public String register(@ModelAttribute(value="securityQuestionViewModel") SecurityQuestionViewModel securityQuestionViewModel) {
Do you need the @ModelAttribute notation. I'm not sure you need it

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +    public void autologin(String password) {
Camel case

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +    public boolean validPassword(String password, String confirm){
This is a bad naming convention, because it is doing more than just validating the password, it is also saving to the Db

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/services/ResetPasswordService.java
> +    public String getQuesetion(){
Typo

2017-03-28 17:50 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/viewModels/ResetPasswordPasswordViewModel.java
> +    private String confirm;
Confirm what? confirmPassword?

2017-03-28 17:52 UTC, AdamStein593 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +    private User user;
Being global ensures that us has to get set in a certain way so that the function can't be called by anyone to change the password of a certain user

2017-03-28 17:55 UTC, bradleymiles17 commented on src/main/java/com/htisolutions/poolref/controllers/ResetPasswordController.java
> +    private User user;
Okay, that is true. Don't use the Id in the methods, but you can get the current user out of the context anyway in each method. Not sure why we need a global

2017-04-03 16:27 UTC, bradleymiles17 approved these changes

2017-04-08 08:33 UTC, bradleymiles17 commented on src/main/resources/templates/register.html
> +                                        <input name="confirmPassword-password" type="password" class="form-control input-lg" placeholder="Confirm Password" required="required" th:field="*{confirmPass
I think this change will break the form submit

2017-04-08 08:43 UTC, merged